//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeeksBankAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int IdRequest { get; set; }
        public decimal Numero1 { get; set; }
        public decimal Numero2 { get; set; }
        public decimal Resultado { get; set; }
        public bool EncontradoEnSecuencia { get; set; }
        public string Usuario { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string IpOrigen { get; set; }
    }
}
